### ISSUE TITLE
Packaging problems

### ISSUE THREAD

**Issue by elpekenin** [adafruit/CircuitPython_Community_Bundle#215]
As diagnosed/solved on [discord](<https://discord.com/channels/327254708534116352/327298996332658690/1248943502998638612>) earlier today (you can thank my `rf"..."` later 😉)

With the current configuration of actions, if the "compilation" to `.mpy` fails, the zip is not generated and `circup` will get broken.

On this very situation it was due to me using a feature that `mpy-cross` does not support (raw fstring), which caused the process to error out. However i wouldnt be surprised if a fail somewhere else in the pipeline also causes this kind of problem.

Probably the easier and best solution is to do some fallback logic as in: 
```py
try:
    latest_zip = run_pipeline()
except:
    latest_zip = previous_one
```

But since i have no idea about GHA (nor perms to do anything) i'm simply noting this so it doesnt get forgotten far in the chat's history

**Comment by jepler** [comment]
We worked on this over in https://github.com/adafruit/adabot/issues/377 so that now any problems should stop a bad bundle from being generated.

In #225 I suggest that we should establish expectations for libraries, such as that they have their own github CI that would detect problems like this. The red X would be an indication to library maintainers that they should resolve it before making a release.

Closing, as I believe this issue has done its job of making sure the issue of completely broken bundle releases has been addressed. Thanks!
